### ISSUE TITLE
Missing Makefile.config

### ISSUE THREAD

**Issue by luckcolors** [ryankennedyio/deep-dream-generator#1]
The Makefile.config is missing in caffe-master.
Logs:
Step 19 : ADD caffe-master /caffe-master
 ---> 6e29214f4a3e
Removing intermediate container 654c0ccf5574
Step 20 : RUN cd /caffe-master && make && make distribute
 ---> Running in 855734ee30d2
Makefile:6: **\* Makefile.config not found. See Makefile.config.example..  Stop.
The command '/bin/sh -c cd /caffe-master && make && make distribute' returned a
non-zero code: 2

**Comment by ryankennedyio** [comment]
Thanks for the pickup. Didn't realise it was in .gitignore.

https://github.com/ryankennedyio/deep-dream-generator/commit/4be05e68b46d8706a1816ba70d0893eadc3e942b

**Comment by luckcolors** [comment]
No problem :D.
