### ISSUE TITLE
This is what I got after running

### ISSUE THREAD

**Issue by karelbilek** [ryankennedyio/deep-dream-generator#11]
This is what I get after successfully compiling and running the docker and logging in.

![Imgur](http://i.imgur.com/JjUaKDF.png)

Clicking "OK" twice shows up empty editor-y looking GUI, where I can't edit anything or save/open anything.

Is this correct?

**Comment by karelbilek** [comment]
The first error is fixable by manually installing mathjax, whatever that is, I will put it as a PR.

The second error I have no idea. In docker logs, I see this

```
2015-07-14 22:33:29.930 [NotebookApp] WARNING | Unreadable Notebook: /notebooks/dream.ipynb Notebook does not appear to be JSON: u'{\n "metadata": {\n  "colabVersion": "...
WARNING:tornado.access:400 GET /api/notebooks/dream.ipynb?_=1436913208816 (10.33.0.116) 10.79ms referer=https://10.33.0.138/notebooks/dream.ipynb
```

Well, ok, that seems like an error.

**Comment by karelbilek** [comment]
...that's because it actually ain't a valid JSON. Will post corrections as pull requests too.

**Comment by karelbilek** [comment]
fixed with #12, #13. The notebook is still unusable out-of-the-box, I will look later what to do with that

**Comment by karelbilek** [comment]
Well, I actually managed it to work (with some edits, I will send them as another PR). Now it only crashes the kernel when it runs out of memory, but I am too lazy to try to fix that :D

**Comment by ryankennedyio** [comment]
Hey @runn1ng can you please do a PR and I'll merge it in?

**Comment by karelbilek** [comment]
I made 3 separate ones. Or do you want to merge all those into one?

(the last one is bigger, since I deleted whole caffe and clone it in docker
instead)

**Comment by karelbilek** [comment]
ahh the sweet 2015 where we were not spammed with midjourney crap
