### ISSUE TITLE
DNScrypt 

### ISSUE THREAD

**Issue by dmitridal** [ryankennedyio/deep-dream-generator#6]
seems like I can not get a connection to download from inside docker, and some command is failing from the backup step with in docker. the message is "build requires 1 argument"
bash-3.2$ docker build -t ryankennedy/deepdream
docker: "build" requires 1 argument.
See 'docker build --help'.

**Comment by ryankennedyio** [comment]
@dmitridal The command you need is 

`docker build -t ryankennedy/deepdream .`

Note the '.', which signifies that you want to build a dockerfile in 'this' directory.

Let me know how it goes.

**Comment by dmitridal** [comment]
that helps, but this seems to fix the problem.....
boot2docker ssh 'sudo /etc/init.d/docker restart'
it was throwing a cert mismatch....
now I am stuck here.
Sending build context to Docker daemon 14.14 MB
Sending build context to Docker daemon 
Step 0 : FROM ipython/ipython:3.x
Pulling repository ipython/ipython
Get https://index.docker.io/v1/repositories/ipython/ipython/images: dial tcp: lookup index.docker.io on 127.0.0.54:53: read udp 127.0.0.54:53: connection refused
progresss....
